# Annotation properties to be considered as descriptions/definitions
annotationURI=http://www.w3.org/2000/01/rdf-schema#comment,http://purl.org/dc/terms/description
ontologyTitle=OntoExhibit
ontologyPrefix=oex
ontologyNamespaceURI=https://w3id.org/OntoExhibit#
ontologyName=OntoExhibit
ontologyURI=https://w3id.org/OntoExhibit#
